model:
  max_epochs: 200

data:
  size: [96,96,96]
  batch_size: 64
  num_workers: 4
  csv_file: "./data/csvs/train.csv"
  val_csv: "./data/csvs/val.csv"
  root_dir:  "./"

simclrvit:
  ckpt_path: "/media/data/divyanshu/BrainIAC_V2/checkpoints/BrainIAC.ckpt"

optim:
  lr: 0.0008
  momentum: 0.9
  weight_decay: 0.0001
  clr: "no"

logger:
  save_dir: "./checkpoints"
  save_name: "best-model-{epoch:02d}-{val_auc:.2f}"
  run_name: "finetune"
  project_name: "fientune"
gpu:
  visible_device: "0" 
train: 
  freeze: "no"
  finetune: "no"
  
 